version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: axe-core
    versions:
    - 4.1.1
    - 4.1.2
    - 4.1.3
    - 4.1.4
  - dependency-name: eslint-config-brightspace
    versions:
    - 0.11.0
    - 0.12.0
    - 0.13.0
    - 0.13.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
